### ISSUE TITLE
All erc20 tests fail following the example instructions

### ISSUE THREAD

**Issue by drewstone** [patractlabs/redspot#171]
**Node version**
14.17.0

**Cargo contract version**
`cargo-contract 0.17.0-unknown-aarch64-macos`

**Canvas node version**
I installed canvas with the following command:
```
cargo install canvas-node --git https://github.com/paritytech/canvas-node.git --tag v0.1.9 --force --locked
```

**Redspot Version**
```
> npx redspot --version
0.13.3
```
I cloned the repo commit `9c612e8afc55e684c57a4a53355e514729aa194e` and did the following:
- `yarn`
- `yarn build`
- `cd examples/erc20`
- `yarn`
- `yarn test`

The output was:
```
  1) ERC20
       Assigns initial balance:
     RedspotPluginError: Instantiation failed
      at /Users/drew/code/redspot/examples/erc20/node_modules/@redspot/patract/contractFactory.js:225:23
      at ContractFactory.instantiateWithCode (node_modules/@redspot/patract/contractFactory.js:221:28)
      at ContractFactory.deploy (node_modules/@redspot/patract/contractFactory.js:272:31)

  2) ERC20
       Transfer adds amount to destination account:
     RedspotPluginError: Instantiation failed
      at /Users/drew/code/redspot/examples/erc20/node_modules/@redspot/patract/contractFactory.js:225:23
      at ContractFactory.instantiateWithCode (node_modules/@redspot/patract/contractFactory.js:221:28)
      at ContractFactory.deploy (node_modules/@redspot/patract/contractFactory.js:272:31)

  3) ERC20
       Transfer emits event:
     RedspotPluginError: Instantiation failed
      at /Users/drew/code/redspot/examples/erc20/node_modules/@redspot/patract/contractFactory.js:225:23
      at ContractFactory.instantiateWithCode (node_modules/@redspot/patract/contractFactory.js:221:28)
      at ContractFactory.deploy (node_modules/@redspot/patract/contractFactory.js:272:31)

  4) ERC20
       Can not transfer above the amount:
     RedspotPluginError: Instantiation failed
      at /Users/drew/code/redspot/examples/erc20/node_modules/@redspot/patract/contractFactory.js:225:23
      at ContractFactory.instantiateWithCode (node_modules/@redspot/patract/contractFactory.js:221:28)
      at ContractFactory.deploy (node_modules/@redspot/patract/contractFactory.js:272:31)

  5) ERC20
       Can not transfer from empty account:
     RedspotPluginError: Instantiation failed
      at /Users/drew/code/redspot/examples/erc20/node_modules/@redspot/patract/contractFactory.js:225:23
      at ContractFactory.instantiateWithCode (node_modules/@redspot/patract/contractFactory.js:221:28)
      at ContractFactory.deploy (node_modules/@redspot/patract/contractFactory.js:272:31)
```

**Comment by ii-ii-ii** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/69485494/154782569-f4d3d242-9712-464f-ba00-5c844e44272c.png">
﻿
There should be some issues with canvas, and it also won't deploy using polkadot/apps.
Canvas may have been abandoned for maintenance, as redspot will no longer support it. use https://github.com/paritytech/substrate-contracts-node instead.
