### ISSUE TITLE
Redspot doesn't work with `polkadot-js` v7.10.1

### ISSUE THREAD

**Issue by xgreenx** [patractlabs/redspot#175]
Redspot doesn't work with a [new release](https://github.com/polkadot-js/api/releases/tag/v7.10.1) of polkadot js

```shell
yarn run v1.22.10
$ npx redspot compile --release
An unexpected error occurred:

TypeError: Cannot read private member #registry from an object whose class did not declare it
    at Proxy.get registry (/Users/green/node_modules/@polkadot/api/base/Decorate.cjs:110:17)
    at Reflect.get (<anonymous>)
    at Object.get (/Users/green/node_modules/redspot/internal/util/lazy.js:142:28)
    at createNetwork (/Users/green/node_modules/redspot/provider/construction.js:45:26)
    at new Environment (/Users/green/node_modules/redspot/internal/core/runtime-environment.js:71:53)
    at main (/Users/green/node_modules/redspot/internal/cli/cli.js:105:21)
npm ERR! code 1
npm ERR! path /Users/green
npm ERR! command failed
npm ERR! command sh -c redspot "compile" "--release"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/green/.npm/_logs/2022-02-27T11_35_20_808Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ntduan** [comment]
We need some time to get compatible with the new version. For now, you can specify an older version of polkadotjs as a dependency via yarn resolutions.

**Comment by ii-ii-ii** [comment]
1.3.6 has been released and should fix the problem

**Comment by xgreenx** [comment]
Yep, it works, thanks
